# Generated by Django 4.2.14 on 2024-07-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_to_peer', '0002_rename_phone_riderprofile_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='username',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
