# Generated by Django 4.2.14 on 2024-07-25 07:18

import django.core.validators
from django.db import migrations, models
import peer_to_peer.models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_to_peer', '0004_usertrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=10, validators=[peer_to_peer.models.validate_phone])),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(max_length=20, validators=[peer_to_peer.models.validate_vehicle_no])),
                ('aadhaar_no', models.CharField(max_length=12, validators=[peer_to_peer.models.validate_aadhaar])),
                ('license_no', models.CharField(max_length=20, validators=[peer_to_peer.models.validate_license_no])),
                ('Username', models.CharField(max_length=30, validators=[peer_to_peer.models.validate_username])),
                ('password', models.CharField(max_length=10, validators=[peer_to_peer.models.validate_password])),
            ],
        ),
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('phone_no', models.CharField(max_length=10, validators=[peer_to_peer.models.validate_phone])),
                ('Username', models.CharField(max_length=30, validators=[peer_to_peer.models.validate_username])),
                ('password', models.CharField(max_length=10, validators=[peer_to_peer.models.validate_password])),
            ],
        ),
    ]
