# Generated by Django 4.2.14 on 2024-07-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_to_peer', '0005_createride_createuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createride',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
