# Generated by Django 4.2.14 on 2024-08-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_to_peer', '0007_maprider_mapuser_createride_gender_createuser_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mapRider',
        ),
        migrations.DeleteModel(
            name='mapUser',
        ),
    ]
