# Generated by Django 4.2.14 on 2024-08-08 13:29

from django.db import migrations, models
import peer_to_peer.models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_to_peer', '0008_delete_maprider_delete_mapuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='priority_no',
            field=models.CharField(default='DEFAULT_PRIORITY', max_length=10, validators=[peer_to_peer.models.validate_phone]),
        ),
    ]
